# Generated by Django 4.2.4 on 2023-10-03 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='نام و نام خانوداگی')),
                ('id_code', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='کد شناسایی')),
                ('father_name', models.CharField(max_length=250, verbose_name='نام پدر')),
                ('history', models.TextField(blank=True, null=True, verbose_name='خاطرات')),
                ('life_history', models.TextField(blank=True, null=True, verbose_name='زندگی نامه')),
                ('devise', models.TextField(blank=True, null=True, verbose_name='وصیت نامه')),
            ],
            options={
                'verbose_name_plural': 'پست ها',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('dataClass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='blog.post')),
            ],
            options={
                'verbose_name_plural': 'عکس ها',
            },
        ),
    ]
